import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";

import "./globals.css";
import "remixicon/fonts/remixicon.css";
import Footer from "@/components/Footer/Footer";

const fontPoppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Company Profile",
  description: "Generated by Coding Sendiri",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${fontPoppins.className} antialiased`} id="beranda">
        <Navbar />
        <div className="container mx-auto px-4">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
